
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.net.java.dev.jna.jna)
    api(libs.org.slf4j.slf4j.simple)
    api(libs.com.profesorfalken.jpowershell)
    testImplementation(libs.junit.junit)
}

group = "com.profesorfalken"
version = "2.2.1"
description = "jSensors"
java.sourceCompatibility = JavaVersion.VERSION_1_8

application {
    mainClass.set("com.profesorfalken.jsensors.JSensors")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}